## Basic Configuration

baseurl = "."
builddrafts = false
canonifyurls = false
languageCode = "en-CA"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Michael Dryden"
title = "Michael Dryden, Software Architect"

theme = "hugo-goa"

## Hugo Built-in Features
# disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
# googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Michael Dryden"
intro = "Father, husband, developer, technology enthusiast, avid sports fan"
description = "Software Architect at Strive Business Solutions in Manitoba, Canada"
authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Portfolio site for Michael Dryden, Software Architect at Strive Business Solutions"
keywords = "portfolio, michael dryden, dryden"

## Social Accounts
[params.social]
github = "mdryden"
linkedin = "michael-dryden-b66808227"
twitter = "michaeldryden"
facebook = "michaeldryden"
reddit = "pudds"
buymeacoffee = "mdryden"

## Extras
[params.extra]
copyright = "© Michael Dryden"
poweredby = true
highlightjs = true
socialmarkup = true
toc = true
displayrssicon = false

## Main Menu
# [[menu.main]]
#     name = "projects"
#     identifier = "projects"
#     weight = 100
#     url = "/projects/"
# [[menu.main]]
#     name = "blog"
#     weight = 200
#     identifier = "blog"
#     url = "/blog/"
# [[menu.main]]
#     name = "about"
#     identifier = "about"
#     weight = 300
#     url = "/about/"