name: Deploy

env:
  BUCKET_NAME: dryden.dev

on:
  workflow_dispatch:

  push:
    branches:
      - "main"
    paths:
      - "www/**"
      - ".github/workflows/deploy.yml"

jobs:
  deploy:
    name: Deploy to GCP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.110.0"
          extended: true

      - name: Regenerate website
        working-directory: www
        run: hugo --minify

      - name: Authenticate gcloud
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

      - name: Setup gcloud
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Deploy to live bucket
        working-directory: www
        run: gsutil -m rsync -r -d public gs://$BUCKET_NAME
